#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import argparse
from datetime import date
from os import path, system
import re
import subprocess

dest_backup = "BACKUP"
prefix_run = ""

def back_all():
  if (prefix_run == ""):
    f_backuped = open(dest_backup + "/.backuped", 'w')
  with open(path.expanduser("~/.global-backup")) as f:
    for line in f:
      line = line.replace("\n", "")
      # remove all blank spaces at the beginning of line
      line = re.sub("^\s*", "", line)
      # remove all blank spaces at the end of line
      line = re.sub("\s*$", "", line)
      print(">> {}".format(line))
      if (path.exists(line)):
        if (path.islink(line)):
          realpath = path.realpath(line)
          print("Warning: {} is a link, adding realpath: {}".format(line, realpath))
          if (prefix_run == ""):
            f_backuped.write("{} -> {}\n".format(line, realpath))
          line = realpath
        else:
          if (prefix_run == ""):
            f_backuped.write("{}\n".format(line))
        dirname, basename = path.split(line)
        back_dir = dest_backup + dirname;
        system("{}mkdir -p {}".format(prefix_run, back_dir))
        line = line.replace(" ", "\\ ")
        system("{}cp -r {} {}".format(prefix_run, line, back_dir))
      else:
        m = re.match("(^-\s*)(.*)", line)
        # Save just symlink if line prefixed by "- "
        if (m != None):
          item = m.group(2)
          if (path.islink(item)):
            print("Saving symlink {}".format(item))
            realpath = path.realpath(item)
            if (prefix_run == ""):
              f_backuped.write("{} -> {}\n".format(item, realpath))
  if (prefix_run == ""):
    f_backuped.close()

def help():
  help = """Use: make_backup [OPTION..] [NAME_BACKUP]
Backup files and folders listed on ~/.global-backup to NAME_BACKUP_date_version or in BACKUP_date_version if used without parameters

Options:
  -c, --compress        Compress the backup in a .tar.gz
  -d, --dry             Dry run, print just all the commands that will be run by make_backup
  -h, --help            Display this help screen
"""
  print(help)


if __name__ == '__main__':
  # Use Custom Parser in order to display a better help screen
  class CustomParser(argparse.ArgumentParser):
    def format_help(self):
      help()
  parser = CustomParser()
  parser.add_argument("dest_backup", nargs='?', default="BACKUP",
                      help="Optional base folder name of backup. Default: BACKUP")
  parser.add_argument("-c", "--compress", action="store_true",
                     help="Compress the backup in a .tar.gz")
  parser.add_argument("-d", "--dry", action="store_true",
                     help="Dry run, print just all the commands that will be run by make_backup")
  args = parser.parse_args()
  dest_backup = args.dest_backup
  today = date.today()
  date_string = "_{}_{}_{}".format(today.year, today.month, today.day)
  dest_backup += date_string
  cmd = "ls | grep {}".format(dest_backup)
  ps = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  output = ps.communicate()[0].decode("utf-8")
  next_v = len(output.split("\n"))
  dest_backup += "_v{}".format(next_v)
  if (args.dry):
    print("The following commands will be run by make_backup : ")
    prefix_run = "echo "
  print("Making backup in folder: {}".format(dest_backup))
  system("{}mkdir -p {}".format(prefix_run, dest_backup))
  back_all()
  if (args.compress):
    dest_backup_targz = dest_backup + ".tar.gz"
    print("Compressing backup in file: {}\nRemoving {}".format(dest_backup_targz, dest_backup))
    system("{}tar --remove-files -cvzf {} {}".format(prefix_run, dest_backup_targz, dest_backup))


